cmake_minimum_required(VERSION 3.22)
include("${CMAKE_CURRENT_LIST_DIR}/../../cmake/NoHeapSymbols.cmake")
if(CASE STREQUAL "lto")
    set(symbols "0003e73c W freertos_hooks.cpp.b5cbc98c\n08000010 T freedom\n")
elseif(CASE STREQUAL "free")
    set(symbols "08000010 T free")
elseif(CASE STREQUAL "unresolved")
    set(symbols "         U malloc\n")
elseif(CASE STREQUAL "new_array")
    set(symbols "08000010 T operator new[](unsigned int)\n")
elseif(CASE STREQUAL "delete_array")
    set(symbols "08000010 T operator delete[](void*, unsigned int)\n")
else()
    message(FATAL_ERROR "Unknown test case")
endif()
firmware_verify_no_heap("${symbols}")
