[workspace]
members = ["crates/gamebox-core", "firmware", "tools/font-subset"]
default-members = ["firmware"]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.96"
license = "MIT"
publish = false

[workspace.dependencies]
cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7"
defmt = "1.0.1"
defmt-rtt = "1.0.0"
embassy-executor = { version = "0.10.0", features = ["defmt", "executor-thread", "platform-cortex-m"] }
embassy-futures = "0.1.2"
embassy-stm32 = { version = "0.6.0", features = ["defmt", "stm32f103c8", "time-driver-any", "unstable-pac"] }
embassy-sync = { version = "0.8.0", features = ["defmt"] }
embassy-time = { version = "0.5.1", features = ["defmt"] }
embedded-graphics = "0.8.2"
gamebox-core = { path = "crates/gamebox-core" }
panic-probe = { version = "1.0.0", features = ["print-defmt"] }
static_cell = "2"

[profile.dev]
debug = 2
opt-level = 1

[profile.release]
codegen-units = 1
debug = 1
incremental = false
lto = "fat"
opt-level = "z"
overflow-checks = true

[profile.test]
opt-level = 2
