//! Convert the legacy one-glyph-per-line C table into a sorted Rust subset.

use std::{
    collections::{BTreeMap, BTreeSet},
    env, fs,
    path::Path,
    process::ExitCode,
};

fn main() -> ExitCode {
    match run() {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("font-subset: {error}");
            ExitCode::FAILURE
        }
    }
}

fn run() -> Result<(), String> {
    let mut args = env::args_os().skip(1);
    let source_path = args
        .next()
        .ok_or("usage: font-subset <OLED_Data_Hanzi.c> <charset.txt> <generated.rs>")?;
    let charset_path = args
        .next()
        .ok_or("usage: font-subset <OLED_Data_Hanzi.c> <charset.txt> <generated.rs>")?;
    let output_path = args
        .next()
        .ok_or("usage: font-subset <OLED_Data_Hanzi.c> <charset.txt> <generated.rs>")?;
    if args.next().is_some() {
        return Err("too many arguments".into());
    }

    let source = read_utf8(&source_path)?;
    let charset = read_utf8(&charset_path)?;
    let available = parse_c_table(&source)?;
    let requested: BTreeSet<char> = charset
        .chars()
        .filter(|character| !character.is_ascii() && !character.is_whitespace())
        .collect();

    let missing: String = requested
        .iter()
        .filter(|character| !available.contains_key(character))
        .collect();
    if !missing.is_empty() {
        return Err(format!(
            "source table is missing requested glyphs: {missing}"
        ));
    }

    let mut output = String::from(
        "// @generated by tools/font-subset; do not edit by hand.\n\
         // Source bitmap format: 16 columns x two vertical 8-pixel pages.\n\
         pub(super) static GLYPHS: &[Glyph] = &[\n",
    );
    for character in requested {
        let bitmap = available
            .get(&character)
            .ok_or_else(|| format!("internal lookup failure for {character}"))?;
        output.push_str(&format!("    Glyph {{ character: {character:?}, bitmap: ["));
        for (index, byte) in bitmap.iter().enumerate() {
            if index != 0 {
                output.push_str(", ");
            }
            output.push_str(&format!("0x{byte:02x}"));
        }
        output.push_str("] },\n");
    }
    output.push_str("];\n");

    fs::write(&output_path, output).map_err(|error| {
        format!(
            "cannot write {}: {error}",
            Path::new(&output_path).display()
        )
    })?;
    println!(
        "generated {} glyphs ({} firmware bytes) at {}",
        requested_count(&charset),
        requested_count(&charset) * 32,
        Path::new(&output_path).display()
    );
    Ok(())
}

fn requested_count(charset: &str) -> usize {
    charset
        .chars()
        .filter(|character| !character.is_ascii() && !character.is_whitespace())
        .collect::<BTreeSet<_>>()
        .len()
}

fn read_utf8(path: &std::ffi::OsStr) -> Result<String, String> {
    fs::read_to_string(path)
        .map_err(|error| format!("cannot read {}: {error}", Path::new(path).display()))
}

fn parse_c_table(source: &str) -> Result<BTreeMap<char, [u8; 32]>, String> {
    let mut glyphs = BTreeMap::new();
    for (line_number, line) in source.lines().enumerate() {
        let Some(quote_start) = line.find('"') else {
            continue;
        };
        let Some(relative_end) = line[quote_start + 1..].find('"') else {
            continue;
        };
        let label = &line[quote_start + 1..quote_start + 1 + relative_end];
        let mut characters = label.chars();
        let Some(character) = characters.next() else {
            continue;
        };
        if characters.next().is_some() {
            continue;
        }

        let values: Result<Vec<u8>, _> = line[..quote_start]
            .split(',')
            .filter_map(|token| {
                let token = token.trim();
                token
                    .strip_prefix("0x")
                    .or_else(|| token.strip_prefix("0X"))
                    .map(|hex| u8::from_str_radix(hex, 16))
            })
            .collect();
        let values = values
            .map_err(|error| format!("invalid byte on source line {}: {error}", line_number + 1))?;
        if values.len() != 32 {
            return Err(format!(
                "glyph {character} on source line {} has {} bytes, expected 32",
                line_number + 1,
                values.len()
            ));
        }
        let bitmap: [u8; 32] = values
            .try_into()
            .map_err(|_| format!("cannot form bitmap for {character}"))?;
        glyphs.entry(character).or_insert(bitmap);
    }
    if glyphs.is_empty() {
        return Err("no glyphs found in source table".into());
    }
    Ok(glyphs)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parser_reads_one_legacy_row() {
        let mut row = String::new();
        for value in 0..32 {
            row.push_str(&format!("0x{value:02x},"));
        }
        row.push_str("\"中\",//0");
        let table = parse_c_table(&row).unwrap();
        assert_eq!(table[&'中'][31], 31);
    }
}
