[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32F103C8Tx"
rustflags = ["-C", "link-arg=-Tlink.x", "-C", "link-arg=-Tdefmt.x"]

[build]
target = "thumbv7m-none-eabi"

[alias]
xtask = "run --locked --package xtask --profile xtask --target host-tuple --"
build-spi = "xtask build --display spi --release"
build-i2c = "xtask build --display i2c --release"
build-all = "xtask build --display all --release"

[env]
DEFMT_LOG = "info"

