cmake_minimum_required(VERSION 3.22)
# Integration regressions require a Release-SPI package from the normal build.
get_filename_component(project_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(source "${project_root}/artifacts/firmware/release/gamebox-f103-spi.elf")
set(test_root "${project_root}/build/artifact regression")
set(package "${test_root}/firmware/release/gamebox-f103-spi")
set(common -DDISPLAY=SPI -DPROFILE=Release "-DOUTPUT_ROOT=${test_root}/firmware"
    "-DSCRATCH=${test_root}/stage" "-DELF=${source}")
set(script "${project_root}/cmake/PackageFirmware.cmake")
find_program(OBJCOPY arm-none-eabi-objcopy REQUIRED)
include("${project_root}/cmake/ValidateFirmware.cmake")
firmware_validate_elf("${source}" ignored_flash ignored_ram original_entry)
function(package_run mode expect_success)
    execute_process(COMMAND "${CMAKE_COMMAND}" ${common} "-DMODE=${mode}" ${ARGN}
        -P "${script}" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(expect_success AND NOT result EQUAL 0)
        message(FATAL_ERROR "Expected ${mode} success: ${output}\n${error}")
    elseif(NOT expect_success AND result EQUAL 0)
        message(FATAL_ERROR "Expected ${mode} to reject the damaged package")
    endif()
endfunction()
package_run(EXPORT TRUE)
package_run(VERIFY TRUE)
foreach(extension IN ITEMS elf bin hex json sha256)
    file(SHA256 "${package}.${extension}" original_${extension})
endforeach()

# Export the same cached ELF after removing only the package BIN.
file(REMOVE "${package}.bin")
package_run(EXPORT TRUE)
foreach(extension IN ITEMS elf bin hex json sha256)
    file(SHA256 "${package}.${extension}" actual)
    if(NOT actual STREQUAL original_${extension})
        message(FATAL_ERROR "Cached export changed ${extension}")
    endif()
endforeach()

# A conversion failure must preserve every previously published byte.
package_run(EXPORT FALSE "-DOBJCOPY=${test_root}/missing-objcopy")
foreach(extension IN ITEMS elf bin hex json sha256)
    file(SHA256 "${package}.${extension}" actual)
    if(NOT actual STREQUAL original_${extension})
        message(FATAL_ERROR "Failed conversion damaged published ${extension}")
    endif()
endforeach()

# A well-formed ELF with a reset entry or load address outside the program
# region must fail independently of package hashes and HEX conversion.
foreach(case IN ITEMS reset flash)
    if(case STREQUAL "reset")
        set(change --set-start=0x0800f801)
    else()
        set(change --change-addresses=0x20000 "--set-start=${original_entry}")
    endif()
    execute_process(COMMAND "${OBJCOPY}" ${change} "${source}" "${test_root}/invalid-${case}.elf"
        RESULT_VARIABLE changed ERROR_VARIABLE error)
    if(NOT changed EQUAL 0)
        message(FATAL_ERROR "Unable to prepare ${case} regression: ${error}")
    endif()
    package_run(EXPORT FALSE "-DELF=${test_root}/invalid-${case}.elf")
endforeach()
foreach(extension IN ITEMS elf bin hex json sha256)
    file(SHA256 "${package}.${extension}" actual)
    if(NOT actual STREQUAL original_${extension})
        message(FATAL_ERROR "Rejected ELF damaged published ${extension}")
    endif()
endforeach()
file(APPEND "${package}.bin" "damaged")
package_run(VERIFY FALSE)
package_run(EXPORT TRUE)
package_run(VERIFY TRUE)
message(STATUS "Artifact regressions passed: paths with spaces, cached export, failed conversion, ELF reset/Flash bounds, corruption detection")
