cmake_minimum_required(VERSION 3.22)
# Portable entry point: cmake [-DMODE=CI|BUILD|TEST|CHECK|VERIFY] [-DDISPLAY=ALL|SPI|I2C]
#                          [-DPROFILE=ALL|Debug|Release] -P scripts/verify.cmake
get_filename_component(project_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
if(NOT DEFINED MODE)
    set(MODE CI)
endif()
if(NOT DEFINED DISPLAY)
    set(DISPLAY ALL)
endif()
if(NOT DEFINED PROFILE)
    set(PROFILE ALL)
endif()
string(TOUPPER "${MODE}" MODE)
string(TOUPPER "${DISPLAY}" DISPLAY)
string(TOUPPER "${PROFILE}" PROFILE)
if(NOT MODE MATCHES "^(CI|BUILD|TEST|CHECK|VERIFY)$")
    message(FATAL_ERROR "MODE must be CI, BUILD, TEST, CHECK, or VERIFY")
endif()
if(DISPLAY STREQUAL "ALL")
    set(displays SPI I2C)
elseif(DISPLAY MATCHES "^(SPI|I2C)$")
    set(displays ${DISPLAY})
else()
    message(FATAL_ERROR "DISPLAY must be ALL, SPI, or I2C")
endif()
if(PROFILE STREQUAL "ALL")
    set(profiles Debug Release)
elseif(PROFILE STREQUAL "DEBUG")
    set(profiles Debug)
elseif(PROFILE STREQUAL "RELEASE")
    set(profiles Release)
else()
    message(FATAL_ERROR "PROFILE must be ALL, Debug, or Release")
endif()
function(run)
    execute_process(COMMAND ${ARGV} WORKING_DIRECTORY "${project_root}"
        RESULT_VARIABLE result)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Verification step failed (${result}): ${ARGV}")
    endif()
endfunction()

if(MODE STREQUAL "CI" OR MODE STREQUAL "TEST")
    run("${CMAKE_COMMAND}" -S tests -B build/HostTests -G Ninja)
    run("${CMAKE_COMMAND}" --build build/HostTests --parallel)
    run("${CMAKE_CTEST_COMMAND}" --test-dir build/HostTests --output-on-failure)
endif()
if(MODE STREQUAL "CI" OR MODE STREQUAL "BUILD")
    foreach(display IN LISTS displays)
        foreach(profile IN LISTS profiles)
            set(preset "${profile}-${display}")
            run("${CMAKE_COMMAND}" --preset "${preset}")
            run("${CMAKE_COMMAND}" --build --preset "${preset}" --parallel)
            run("${CMAKE_CTEST_COMMAND}" --test-dir "build/${preset}" --output-on-failure)
        endforeach()
    endforeach()
endif()
if(MODE STREQUAL "CI" OR MODE STREQUAL "CHECK")
    foreach(display IN LISTS displays)
        run("${CMAKE_COMMAND}" --preset "Analyze-${display}")
        run("${CMAKE_COMMAND}" --build --preset "Analyze-${display}" --parallel)
    endforeach()
endif()
if(MODE STREQUAL "CI" AND "SPI" IN_LIST displays AND "Release" IN_LIST profiles)
    run("${CMAKE_COMMAND}" -P scripts/test_artifacts.cmake)
endif()
if(MODE STREQUAL "VERIFY")
    foreach(display IN LISTS displays)
        foreach(profile IN LISTS profiles)
            run("${CMAKE_COMMAND}" -DMODE=VERIFY "-DDISPLAY=${display}"
                "-DPROFILE=${profile}" "-DOUTPUT_ROOT=${project_root}/artifacts/firmware"
                "-DSCRATCH=${project_root}/build/verify-artifacts/${profile}-${display}"
                -P "${project_root}/cmake/PackageFirmware.cmake")
        endforeach()
    endforeach()
endif()
