cmake_minimum_required(VERSION 3.22)
foreach(required IN ITEMS MODE DISPLAY PROFILE OUTPUT_ROOT SCRATCH)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "PackageFirmware.cmake requires ${required}")
    endif()
endforeach()
string(TOLOWER "${DISPLAY}" display)
string(TOLOWER "${PROFILE}" profile)
if(NOT display MATCHES "^(spi|i2c)$" OR NOT profile MATCHES "^(debug|release)$")
    message(FATAL_ERROR "Expected SPI/I2C and Debug/Release package selection")
endif()
if(NOT DEFINED OBJCOPY)
    find_program(OBJCOPY arm-none-eabi-objcopy REQUIRED)
endif()
if(NOT DEFINED NM)
    find_program(NM arm-none-eabi-gcc-nm REQUIRED)
endif()
include("${CMAKE_CURRENT_LIST_DIR}/ValidateFirmware.cmake")
set(stem "gamebox-f103-${display}")
set(destination "${OUTPUT_ROOT}/${profile}")
set(names "${stem}.elf" "${stem}.bin" "${stem}.hex")
if(MODE STREQUAL "EXPORT")
    if(NOT DEFINED ELF OR NOT EXISTS "${ELF}")
        message(FATAL_ERROR "Export requires an existing firmware ELF")
    endif()
    file(MAKE_DIRECTORY "${SCRATCH}")
    configure_file("${ELF}" "${SCRATCH}/${stem}.elf" COPYONLY)
    foreach(format IN ITEMS binary ihex)
        if(format STREQUAL "binary")
            set(extension bin)
        else()
            set(extension hex)
        endif()
        execute_process(COMMAND "${OBJCOPY}" -O ${format}
            "${SCRATCH}/${stem}.elf" "${SCRATCH}/${stem}.${extension}"
            RESULT_VARIABLE converted ERROR_VARIABLE error)
        if(NOT converted EQUAL 0)
            message(FATAL_ERROR "Conversion failed; existing package preserved: ${error}")
        endif()
    endforeach()
    set(package "${SCRATCH}")
elseif(MODE STREQUAL "VERIFY")
    set(package "${destination}")
else()
    message(FATAL_ERROR "MODE must be EXPORT or VERIFY")
endif()

if(MODE STREQUAL "VERIFY")
    file(READ "${package}/${stem}.json" manifest)
    foreach(field IN ITEMS display profile target flash_base settings_reserved)
        string(JSON actual_${field} GET "${manifest}" ${field})
    endforeach()
    if(NOT actual_display STREQUAL display OR NOT actual_profile STREQUAL profile
       OR NOT actual_target STREQUAL "thumbv7m-none-eabi"
       OR NOT actual_flash_base STREQUAL "0x08000000"
       OR NOT actual_settings_reserved STREQUAL "0x0800F800..0x08010000")
        message(FATAL_ERROR "Package metadata does not match the selected firmware")
    endif()
    string(JSON count LENGTH "${manifest}" files)
    if(NOT count EQUAL 3)
        message(FATAL_ERROR "Unexpected package file count")
    endif()
    set(index 0)
    foreach(name IN LISTS names)
        string(JSON actual_name GET "${manifest}" files ${index} file)
        string(JSON actual_bytes GET "${manifest}" files ${index} bytes)
        string(JSON actual_hash GET "${manifest}" files ${index} sha256)
        # Never use a filename from the manifest to access the filesystem.
        file(SIZE "${package}/${name}" bytes)
        file(SHA256 "${package}/${name}" hash)
        if(NOT actual_name STREQUAL name OR NOT actual_bytes EQUAL bytes
           OR NOT actual_hash STREQUAL hash)
            message(FATAL_ERROR "Package filename/size/SHA256 mismatch: ${name}")
        endif()
        math(EXPR index "${index} + 1")
    endforeach()
endif()

firmware_validate_images("${package}/${stem}.elf" "${package}/${stem}.bin"
    "${package}/${stem}.hex" "${SCRATCH}" flash_bytes ram_bytes)
if(MODE STREQUAL "EXPORT")
    set(manifest "{\n  \"display\": \"${display}\",\n  \"profile\": \"${profile}\",\n")
    string(APPEND manifest "  \"target\": \"thumbv7m-none-eabi\",\n")
    string(APPEND manifest "  \"flash_base\": \"0x08000000\",\n")
    string(APPEND manifest "  \"settings_reserved\": \"0x0800F800..0x08010000\",\n")
    string(APPEND manifest "  \"flash_bytes\": ${flash_bytes},\n  \"static_ram_bytes\": ${ram_bytes},\n  \"files\": [\n")
    set(separator "")
    set(checksums "")
    foreach(name IN LISTS names)
        file(SIZE "${package}/${name}" bytes)
        file(SHA256 "${package}/${name}" hash)
        string(APPEND manifest "${separator}    {\"file\": \"${name}\", \"bytes\": ${bytes}, \"sha256\": \"${hash}\"}")
        string(APPEND checksums "${hash}  ${name}\n")
        set(separator ",\n")
    endforeach()
    string(APPEND manifest "\n  ]\n}\n")
    file(WRITE "${SCRATCH}/${stem}.json" "${manifest}")
    file(WRITE "${SCRATCH}/${stem}.sha256" "${checksums}")
    # All conversions and checks succeeded. Publish the manifest last, so an
    # interrupted publication is detectable by the next verification.
    file(MAKE_DIRECTORY "${destination}")
    foreach(name IN LISTS names)
        configure_file("${SCRATCH}/${name}" "${destination}/${name}" COPYONLY)
    endforeach()
    configure_file("${SCRATCH}/${stem}.sha256" "${destination}/${stem}.sha256" COPYONLY)
    configure_file("${SCRATCH}/${stem}.json" "${destination}/${stem}.json" COPYONLY)
else()
    string(JSON actual_flash GET "${manifest}" flash_bytes)
    string(JSON actual_ram GET "${manifest}" static_ram_bytes)
    if(NOT actual_flash EQUAL flash_bytes OR NOT actual_ram EQUAL ram_bytes)
        message(FATAL_ERROR "Package memory usage does not match ELF layout")
    endif()
    set(checksums "")
    foreach(name IN LISTS names)
        file(SHA256 "${package}/${name}" hash)
        string(APPEND checksums "${hash}  ${name}\n")
    endforeach()
    file(READ "${package}/${stem}.sha256" actual_checksums)
    if(NOT actual_checksums STREQUAL checksums)
        message(FATAL_ERROR "SHA256 checksum file does not match package")
    endif()
endif()
message(STATUS "${MODE} ${display} ${profile}: Flash ${flash_bytes}/63488 B, SRAM ${ram_bytes}/20480 B -> ${destination}")
