# Dependency-free readers for the STM32F103C8 Cortex-M3 image contract.
# Inspect ELF metadata directly; do not trust objcopy to enforce board bounds.
function(firmware_read_le path offset width output)
    file(READ "${path}" bytes OFFSET ${offset} LIMIT ${width} HEX)
    string(LENGTH "${bytes}" actual)
    math(EXPR expected "${width} * 2")
    if(NOT actual EQUAL expected)
        message(FATAL_ERROR "Truncated firmware header in ${path}")
    endif()
    set(value 0)
    math(EXPR last "${width} - 1")
    foreach(index RANGE 0 ${last})
        math(EXPR start "${index} * 2")
        string(SUBSTRING "${bytes}" ${start} 2 byte)
        math(EXPR value "${value} | (0x${byte} << (${index} * 8))")
    endforeach()
    set(${output} ${value} PARENT_SCOPE)
endfunction()

function(firmware_validate_elf elf flash_output ram_output entry_output)
    file(SIZE "${elf}" elf_size)
    file(READ "${elf}" ident LIMIT 7 HEX)
    if(NOT ident STREQUAL "7f454c46010101")
        message(FATAL_ERROR "Expected a 32-bit little-endian ELF: ${elf}")
    endif()
    firmware_read_le("${elf}" 16 2 elf_type)
    firmware_read_le("${elf}" 18 2 machine)
    firmware_read_le("${elf}" 24 4 entry)
    firmware_read_le("${elf}" 28 4 phoff)
    firmware_read_le("${elf}" 42 2 phsize)
    firmware_read_le("${elf}" 44 2 phcount)
    math(EXPR thumb "${entry} & 1")
    math(EXPR reset "${entry} & ~1")
    if(NOT elf_type EQUAL 2 OR NOT machine EQUAL 40 OR NOT thumb EQUAL 1
       OR reset LESS 0x08000000 OR reset GREATER_EQUAL 0x0800f800)
        message(FATAL_ERROR "Invalid ARM executable or Cortex-M reset entry")
    endif()
    math(EXPR phend "${phoff} + ${phsize} * ${phcount}")
    if(phsize LESS 32 OR phcount LESS 1 OR phend GREATER elf_size)
        message(FATAL_ERROR "Invalid ELF program-header table")
    endif()
    set(first 0xffffffff)
    set(flash_end 0x08000000)
    set(ram_end 0x20000000)
    set(reset_loaded FALSE)
    math(EXPR last "${phcount} - 1")
    foreach(index RANGE 0 ${last})
        math(EXPR header "${phoff} + ${index} * ${phsize}")
        firmware_read_le("${elf}" ${header} 4 type)
        if(NOT type EQUAL 1)
            continue()
        endif()
        foreach(field IN ITEMS offset virtual physical file_size memory_size flags)
            math(EXPR header "${header} + 4")
            firmware_read_le("${elf}" ${header} 4 ${field})
        endforeach()
        math(EXPR file_end "${offset} + ${file_size}")
        math(EXPR load_end "${physical} + ${file_size}")
        math(EXPR memory_end "${virtual} + ${memory_size}")
        if(file_size GREATER memory_size OR file_end GREATER elf_size)
            message(FATAL_ERROR "Invalid ELF load-segment size")
        endif()
        if(file_size GREATER 0)
            if(physical LESS 0x08000000 OR load_end GREATER 0x0800f800)
                message(FATAL_ERROR "ELF load segment enters reserved Flash or lies outside program Flash")
            endif()
            if(physical LESS first)
                set(first ${physical})
            endif()
            if(load_end GREATER flash_end)
                set(flash_end ${load_end})
            endif()
            math(EXPR executable "${flags} & 1")
            math(EXPR executable_end "${virtual} + ${file_size}")
            if(executable AND NOT reset LESS virtual AND reset LESS executable_end)
                set(reset_loaded TRUE)
            endif()
        endif()
        if(memory_size GREATER 0)
            if(NOT virtual LESS 0x20000000 AND NOT memory_end GREATER 0x20005000)
                if(memory_end GREATER ram_end)
                    set(ram_end ${memory_end})
                endif()
            elseif(virtual LESS 0x08000000 OR memory_end GREATER 0x0800f800)
                message(FATAL_ERROR "ELF memory segment is outside program Flash/SRAM")
            endif()
        endif()
    endforeach()
    if(NOT first EQUAL 0x08000000 OR NOT reset_loaded)
        message(FATAL_ERROR "ELF must contain vectors at 0x08000000 and an executable reset handler")
    endif()
    math(EXPR flash_bytes "${flash_end} - 0x08000000")
    math(EXPR ram_bytes "${ram_end} - 0x20000000")
    set(${flash_output} ${flash_bytes} PARENT_SCOPE)
    set(${ram_output} ${ram_bytes} PARENT_SCOPE)
    set(${entry_output} ${entry} PARENT_SCOPE)
endfunction()

function(firmware_validate_hex hex bin expected_entry)
    file(READ "${bin}" binary HEX)
    file(SIZE "${bin}" binary_size)
    string(REPEAT "00" ${binary_size} decoded)
    file(STRINGS "${hex}" records NO_HEX_CONVERSION)
    set(base 0)
    set(first 0xffffffff)
    set(end 0)
    set(eof FALSE)
    foreach(record IN LISTS records)
        if(record STREQUAL "")
            continue()
        endif()
        if(eof OR NOT record MATCHES "^:[0-9a-fA-F]+$")
            message(FATAL_ERROR "Invalid HEX record, or data after EOF")
        endif()
        string(LENGTH "${record}" length)
        if(length LESS 11)
            message(FATAL_ERROR "Truncated HEX record")
        endif()
        string(SUBSTRING "${record}" 1 2 count_hex)
        string(SUBSTRING "${record}" 3 4 offset_hex)
        string(SUBSTRING "${record}" 7 2 type_hex)
        math(EXPR count "0x${count_hex}")
        math(EXPR offset "0x${offset_hex}")
        math(EXPR type "0x${type_hex}")
        math(EXPR expected_length "11 + 2 * ${count}")
        if(NOT length EQUAL expected_length)
            message(FATAL_ERROR "Invalid HEX record length")
        endif()
        set(checksum 0)
        math(EXPR last "${length} - 2")
        foreach(position RANGE 1 ${last} 2)
            string(SUBSTRING "${record}" ${position} 2 byte)
            math(EXPR checksum "(${checksum} + 0x${byte}) & 255")
        endforeach()
        if(NOT checksum EQUAL 0)
            message(FATAL_ERROR "Invalid HEX checksum")
        endif()
        math(EXPR data_length "${count} * 2")
        string(SUBSTRING "${record}" 9 ${data_length} data)
        if(type EQUAL 0)
            math(EXPR address "${base} + ${offset}")
            math(EXPR limit "${address} + ${count}")
            math(EXPR image_limit "0x08000000 + ${binary_size}")
            if(address LESS 0x08000000 OR limit GREATER image_limit OR limit GREATER 0x0800f800)
                message(FATAL_ERROR "HEX address lies outside firmware Flash image")
            endif()
            if(count GREATER 0)
                # Our objcopy packages are ordered. Reject repeated/overlapping
                # writes instead of accepting a later record that masks an
                # earlier write to the same NOR Flash address.
                if(address LESS end)
                    message(FATAL_ERROR "HEX data records overlap or are out of order")
                endif()
                if(address LESS first)
                    set(first ${address})
                endif()
                if(limit GREATER end)
                    set(end ${limit})
                endif()
                math(EXPR position "(${address} - 0x08000000) * 2")
                math(EXPR suffix_position "${position} + ${data_length}")
                string(SUBSTRING "${decoded}" 0 ${position} prefix)
                string(SUBSTRING "${decoded}" ${suffix_position} -1 suffix)
                set(decoded "${prefix}${data}${suffix}")
            endif()
        elseif(type EQUAL 1)
            if(NOT count EQUAL 0 OR NOT offset EQUAL 0)
                message(FATAL_ERROR "Invalid HEX EOF record")
            endif()
            set(eof TRUE)
        elseif(type EQUAL 2 OR type EQUAL 4)
            if(NOT count EQUAL 2 OR NOT offset EQUAL 0)
                message(FATAL_ERROR "Invalid HEX address record")
            endif()
            if(type EQUAL 4)
                math(EXPR base "0x${data} << 16")
            else()
                math(EXPR base "0x${data} << 4")
            endif()
        elseif(type EQUAL 5)
            if(NOT count EQUAL 4 OR NOT offset EQUAL 0)
                message(FATAL_ERROR "Invalid HEX entry record")
            endif()
            math(EXPR entry "0x${data}")
            if(NOT entry EQUAL expected_entry)
                message(FATAL_ERROR "HEX entry does not match ELF reset entry")
            endif()
        else()
            message(FATAL_ERROR "Unsupported HEX record type ${type}")
        endif()
    endforeach()
    string(TOLOWER "${decoded}" decoded)
    math(EXPR expected_end "0x08000000 + ${binary_size}")
    if(NOT eof OR NOT first EQUAL 0x08000000 OR NOT end EQUAL expected_end
       OR NOT decoded STREQUAL binary)
        message(FATAL_ERROR "HEX/BIN mismatch, missing vectors, or missing EOF")
    endif()
endfunction()

function(firmware_validate_images elf bin hex scratch flash_output ram_output)
    firmware_validate_elf("${elf}" flash_bytes ram_bytes entry)
    file(SIZE "${bin}" bin_size)
    if(NOT bin_size EQUAL flash_bytes OR bin_size LESS 8)
        message(FATAL_ERROR "BIN length does not match ELF load addresses")
    endif()
    firmware_read_le("${bin}" 0 4 stack)
    firmware_read_le("${bin}" 4 4 reset)
    math(EXPR stack_alignment "${stack} & 7")
    if(NOT stack GREATER 0x20000000 OR stack GREATER 0x20005000
       OR NOT stack_alignment EQUAL 0 OR NOT reset EQUAL entry)
        message(FATAL_ERROR "Invalid initial stack pointer or reset vector")
    endif()
    file(MAKE_DIRECTORY "${scratch}")
    execute_process(COMMAND "${OBJCOPY}" -O binary "${elf}" "${scratch}/check.bin"
        RESULT_VARIABLE converted ERROR_VARIABLE error)
    if(NOT converted EQUAL 0)
        message(FATAL_ERROR "ELF conversion failed: ${error}")
    endif()
    file(SHA256 "${scratch}/check.bin" elf_hash)
    file(SHA256 "${bin}" bin_hash)
    file(REMOVE "${scratch}/check.bin")
    if(NOT elf_hash STREQUAL bin_hash)
        message(FATAL_ERROR "ELF/BIN mismatch")
    endif()
    firmware_validate_hex("${hex}" "${bin}" ${entry})
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DNM=${NM}" "-DELF=${elf}"
        -P "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/VerifyNoHeap.cmake"
        RESULT_VARIABLE heap_result)
    if(NOT heap_result EQUAL 0)
        message(FATAL_ERROR "ELF heap audit failed")
    endif()
    set(${flash_output} ${flash_bytes} PARENT_SCOPE)
    set(${ram_output} ${ram_bytes} PARENT_SCOPE)
endfunction()
