[package]
name = "gamebox-f103-firmware"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
build = "build.rs"

[lib]
bench = false
test = false

[[bin]]
name = "gamebox-f103"
path = "src/main.rs"
bench = false
test = false

[dependencies]
cortex-m.workspace = true
cortex-m-rt.workspace = true
defmt.workspace = true
defmt-rtt.workspace = true
embassy-executor.workspace = true
embassy-futures.workspace = true
embassy-stm32.workspace = true
embassy-sync.workspace = true
embassy-time.workspace = true
gamebox-core.workspace = true
oled-driver = { workspace = true, features = ["async"] }
panic-probe.workspace = true
static_cell.workspace = true
